### ISSUE TITLE
longestPrefix implementation

### ISSUE THREAD

**Issue by Alexander-N** [mitchellh/tlaplus-radix-tree#1]
Thank you for sharing this, I really enjoyed reading [RadixIteratorValidation.tla](https://github.com/mitchellh/tlaplus-radix-tree/blob/main/RadixIteratorValidation.tla)! I found it nice and readable, the only thing that was a bit hard for me to follow was `longestPrefix`, especially the `<=` in
https://github.com/mitchellh/tlaplus-radix-tree/blob/7bb8284cca78be013711a2a631393189a554723f/RadixTrees.tla#L56
was tripping me up, I think it would be clearer to just use `=`.

I saw in [this comment](https://gist.github.com/mitchellh/35836d98385fe2c0f0846cc100492224#gistcomment-3797065) that you prefer this implementation over the approach suggested by @hwayne and was wondering about the reasons? It seems like it would make the implementation simpler, e.g.
```TLA
Max(S) == CHOOSE x \in S: 
            \A y \in S: 
              y <= x
longestPrefix(set) ==
  LET seq == shortestSeq(set)
      lenghts == {0} \union {
        i \in 1..Len(seq):
          \A s \in set: SubSeq(s, 1, i) = SubSeq(seq, 1, i)
      }
  IN SubSeq(seq, 1, Max(lenghts))
```

**Comment by mitchellh** [comment]
I have nothing against that implementation, I just wanted to study it a bit more since it wasn't obvious at the time and I haven't had a chance to do so yet.

**Comment by mitchellh** [comment]
I updated the implementation. 😄
